# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Pravilniki2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mkzcontianer-hkbtaya7fyf7cqgg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_017b0b18311f4a92b024fa3c16295504 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_05d8565d6f834cc2b546b483c4050d52 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mkzcontianer-hkbtaya7fyf7cqgg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_017b0b18311f4a92b024fa3c16295504 }}/custom-azure-ai-chat-app-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Pravilniki2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_80533629ed8b499d997bec0c6dfa7548 }}
        images: 'mkzcontianer-hkbtaya7fyf7cqgg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_017b0b18311f4a92b024fa3c16295504 }}/custom-azure-ai-chat-app-image:${{ github.sha }}'